// DO NOT MODIFY!
// Generated by mb-ormapper generator ver 2.2
// https://github.com/tmurakam/mb-ormapper

#import <UIKit/UIKit.h>
#import "ORRecord.h"

@class Asset;

@interface AssetBase : ORRecord

@property(nonatomic,strong) NSString* name;
@property(nonatomic,assign) NSInteger type;
@property(nonatomic,assign) double initialBalance;
@property(nonatomic,assign) NSInteger sorder;
@property(nonatomic,strong) NSString* identifier;

+ (BOOL)migrate;

// CRUD (Create/Read/Update/Delete) operations

// Read operations (Finder)
+ (Asset *)find:(NSInteger)pid;

+ (Asset *)find_by_name:(NSString*)key cond:(NSString*)cond;
+ (Asset *)find_by_name:(NSString*)key;
+ (Asset *)find_by_type:(NSInteger)key cond:(NSString*)cond;
+ (Asset *)find_by_type:(NSInteger)key;
+ (Asset *)find_by_initialBalance:(double)key cond:(NSString*)cond;
+ (Asset *)find_by_initialBalance:(double)key;
+ (Asset *)find_by_sorder:(NSInteger)key cond:(NSString*)cond;
+ (Asset *)find_by_sorder:(NSInteger)key;
+ (Asset *)find_by_identifier:(NSString*)key cond:(NSString*)cond;
+ (Asset *)find_by_identifier:(NSString*)key;

+ (NSMutableArray *)find_all:(NSString *)cond;

+ (dbstmt *)gen_stmt:(NSString *)cond;
+ (Asset *)find_first_stmt:(dbstmt *)stmt;
+ (NSMutableArray *)find_all_stmt:(dbstmt *)stmt;

// Delete operations
- (void)delete;
+ (void)delete_cond:(NSString *)cond;
+ (void)delete_all;

// Dump SQL
+ (void)getTableSql:(NSMutableString *)s;
- (void)getInsertSql:(NSMutableString *)s;

@end
