// DO NOT MODIFY!
// Generated by mb-ormapper generator ver 2.1
// https://github.com/tmurakam/mb-ormapper

#import <UIKit/UIKit.h>
#import "ORRecord.h"

@class TCategory;

@interface TCategoryBase : ORRecord {
    NSString* mName;
    int mSorder;
}

@property(nonatomic,strong) NSString* name;
@property(nonatomic,assign) int sorder;

+ (BOOL)migrate;

// CRUD (Create/Read/Update/Delete) operations

// Read operations (Finder)
+ (TCategory *)find:(int)pid;

+ (TCategory *)find_by_name:(NSString*)key cond:(NSString*)cond;
+ (TCategory *)find_by_name:(NSString*)key;
+ (TCategory *)find_by_sorder:(int)key cond:(NSString*)cond;
+ (TCategory *)find_by_sorder:(int)key;

+ (NSMutableArray *)find_all:(NSString *)cond;

+ (dbstmt *)gen_stmt:(NSString *)cond;
+ (TCategory *)find_first_stmt:(dbstmt *)stmt;
+ (NSMutableArray *)find_all_stmt:(dbstmt *)stmt;

// Delete operations
- (void)delete;
+ (void)delete_cond:(NSString *)cond;
+ (void)delete_all;

// Dump SQL
+ (void)getTableSql:(NSMutableString *)s;
- (void)getInsertSql:(NSMutableString *)s;

@end
